### ISSUE TITLE
Is Still Maintained ?

### ISSUE THREAD

**Issue by hyyan** [PolymerElements/iron-location#101]
It this element still maintained??
there are numbers of critical issues and PRS waiting for a response since months?

**Comment by e111077** [comment]
Heya, @hyyan, this element is indeed still maintained, but has recently fallen through the cracks as our small team has been having our attention pulled in many different directions for the last few months (other elements, internal integrations, polymer 3, etc.)

Thanks for expressing your concern over this element, as this helps with our prioritizations
