### ISSUE TITLE
No version set in package.json

### ISSUE THREAD

**Issue by RebeccaStevens** [PolymerElements/iron-location#106]
I can't use this repo with `yarn` as there is no version number in the `package.json` file.

https://github.com/yarnpkg/yarn/pull/5318

**Comment by aomarks** [comment]
Polymer 2.x elements are not published on NPM, so they are not installable with npm or yarn. The package.json exists here only for managing devDependencies and npm scripts. Polymer 3.x elements are published on NPM and have a version (more at https://www.polymer-project.org/blog/2018-01-18-polymer-3-new-preview).
