### ISSUE TITLE
"Demo and API docs" link is broken

### ISSUE THREAD

**Issue by exgalexo** [PolymerElements/iron-location#33]
In the https://github.com/PolymerElements/iron-location/blob/master/README.md, there is a link to
https://elements.polymer-project.org/elements/iron-location

This link is broken, it should probably point to:
https://elements.polymer-project.org/elements/iron-page-url

Or alternatively the iron-page-url should be renamed.

**Comment by rictic** [comment]
Fixed now! Thanks for the bug report!
