### ISSUE TITLE
Bower invalid-meta when installing iron-location

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerElements/iron-location#35]
### Description
Installing iron-location causes bower to message an invalid-meta for the field `main`.

### Expected outcome
No error is shown

### Actual outcome
```
bower new           version for git://github.com/polymerelements/iron-location.git#^0.8.1
bower resolve       git://github.com/polymerelements/iron-location.git#^0.8.1
bower download      https://github.com/polymerelements/iron-location/archive/v0.8.2.tar.gz
bower extract       iron-location#^0.8.1 archive.tar.gz
bower invalid-meta  The "main" field has to contain only 1 file per filetype; found multiple .html files: ["iron-location.html","iron-query-params.html"]
```

### Steps to reproduce
1. `bower install --save polymerelements/iron-location`

### Browsers Affected
N/A
- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by rictic** [comment]
Sadly this is a clash between the bower spec and our catalog, which relies on the `main` field to determine what files to show docs for.

We haven't run into any issues in practice with this, save for the occasional warning. Would reconsider if someone reports a problem in practice.

**Comment by MWalid** [comment]
Hello,
I'm facing the same, did you resolve the issue @TimvdLippe ?
