### ISSUE TITLE
Full page refresh when clicking on a link to the same page

### ISSUE THREAD

**Issue by keanulee** [PolymerElements/iron-location#43]
### Description
Ref https://github.com/Polymer/shop/issues/51

When clicking on a link to the URL you're already on (e.g. link in the tabs to `http://localhost:8080/list/ladies_outerwear` while on the same page), a full page refresh is triggered instead of silently doing nothing. Seems to be because of this code: https://github.com/PolymerElements/iron-location/blob/master/iron-location.html#L321

### Expected outcome

After a normal click (e.g. no modifier keys), the page should not refresh.

### Actual outcome

After a normal click, the page refreshes.

### Live Demo

(Not on shop.polymer-project.org which uses an older version of iron-location, but occurs with fresh `bower install`

### Steps to reproduce

Run shop, click a category, click on the same category.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by ymaz** [comment]
Hey, yeah, defiantly this code, in last version `0.8.4` 
https://github.com/PolymerElements/iron-location/blob/master/iron-location.html#L321

So, the issue when we would like to check that
_If the navigation is to the current page we shouldn't add a history_
but, as well, we do not need to reload the page (app).

So, to achieve this, maybe, we could return something like

`if (fullNormalizedHref === window.location.href) {
        return 'no-history'; //or something like that, to highlight that specific case
      }`

and then inside `_globalOnClick` handler, add extra condition, like
(after line 233)
`    if (href === 'no-history') {
         event.preventDefault();
         return;
      }`

So, actually, in this case _If the navigation is to the current page we shouldn't add a history_ we need to intercept the click.

Thanks

**Comment by ymaz** [comment]
Hi @rictic, @keanulee 
what do you think about code sample above?
I can create an pull-request if needed.

**Comment by rictic** [comment]
@yamaz That's a reasonable approach, and it would work. I ended up just moving the check to see if the new url is the same as the current one to the click handler method, just to keep the contract of `_getSameOriginLinkHref` simple. If we find more cases where we want to completely ignore a link click then it'd be worth revisiting.

**Comment by ymaz** [comment]
@rictic yeah, I've just checked your pull-request, looks pretty nice! Would be great to have one more test to cover this case and adjust old ones to avoid build fails. Thanks! Nice job!

**Comment by rictic** [comment]
Good call, I fixed up the tests and added some more assertions.
