### ISSUE TITLE
[2.0-preview] does not work on IE11 due to missing `new URL`

### ISSUE THREAD

**Issue by sorvell** [PolymerElements/iron-location#75]
The 2.0-preview branch doesn't work out of the box due to reliance on `new URL`. This is no longer polyfilled by [webcomponents](https://github.com/webcomponents/webcomponentsjs) so the element should either not rely on it or require/provide a polyfill.

**Comment by JonathanSidego** [comment]
@sorvell I'm having the same issue here. How are you implementing your polyfill/which one are you using?

**Comment by web-padawan** [comment]
Here is an [example](https://github.com/erikringsmuth/app-router/blob/master/src/app-router.js#L501) of `URL` feature detection which might be useful here.

**Comment by azakus** [comment]
Closed with https://github.com/PolymerElements/iron-location/pull/82
